config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[create new]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to @list
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show destroy ]

  def index
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_url, notice: "Lists was successfully destroyed.", status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all.order(:title) %>
  <%= f.input :comment %>
  <%= f.submit 'Add', class: "btn btn-outline-secondary m-auto"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="text-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#">Watch List</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link active" href="<%= new_list_path %>">Create New List</a>
          </li>
        </ul>
        <form class="search-form">
          <input class="form-control search-input" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="text-center">
          <h1>Movie Lists</h1>
        </div>

        <div class="movie-lists-container">
          <% @lists.each do |list| %>
            <div class="d-flex justify-content-center">
              <%= link_to list.name, list_path(list), class: "btn btn-outline-secondary movie-list-link mt-3"%>
            </div>
          <% end %>

          <div class="text-center mt-3">
            <%= link_to "New List", new_list_path, class: "btn btn-outline-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/lists/new.html.erb
<h1>Create a New List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit  class: 'btn btn-primary' %>
<% end %>


<div>
  <%= link_to "Back to Lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="cards mt-5">
    <ul>
      <% @bookmarks.each do |bookmark| %>
        <li>
          <p>
            <%= bookmark.movie.title %>
          </p>
          <p>
            Overview: <%= bookmark.movie.overview %>
          </p>
          <p>
            Rating: <%= bookmark.movie.rating %>
          </p>
          <img src="<%= bookmark.movie.poster_url %>" alt="Movie Poster">
          <%= link_to lists_path(@list), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
            <i class="fa-solid fa-trash remove"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>


    <div class="text-center mt-3">
      <%= link_to "New movie", new_list_bookmark_path(@list), class: "btn btn-outline-secondary" %>
    </div>

    <div class="text-center mt-3">
      <%= link_to "Back to List", lists_path, class: "btn btn-outline-secondary"%>
    </div>

</div>